// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Shop BE Swagger Docs",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "Get list of products",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/IProductsData"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/IErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "Get product by id",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "400": {
            "description": "Bad request response",
            "schema": {
              "$ref": "#/definitions/IErrorResponse"
            }
          },
          "404": {
            "description": "Product not found response",
            "schema": {
              "$ref": "#/definitions/INotFoundResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/IErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "IProduct": {
      "properties": {
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "title": {
          "title": "IProduct.title",
          "type": "string"
        },
        "image": {
          "title": "IProduct.image",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "image",
        "price"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    },
    "IProductsData": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/IProduct",
            "title": "IProductsData.products.[]"
          },
          "title": "IProductsData.products",
          "type": "array"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "IProductsData",
      "type": "object"
    },
    "INotFoundResponse": {
      "properties": {
        "message": {
          "title": "INotFoundResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "INotFoundResponse",
      "type": "object"
    },
    "IErrorResponse": {
      "properties": {
        "error": {
          "title": "IErrorResponse.error",
          "type": "string"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "IErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};