// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Shop BE Swagger Docs",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "Get list of products",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/ProductsData"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "summary": "Create product",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success response"
          },
          "400": {
            "description": "Invalid data response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "Get product by id",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Bad request response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Product not found response",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "image",
        "price"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Stock": {
      "properties": {
        "product_id": {
          "title": "Stock.product_id",
          "type": "string"
        },
        "count": {
          "title": "Stock.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "Stock",
      "type": "object"
    },
    "ProductFull": {
      "properties": {
        "id": {
          "title": "ProductFull.id",
          "type": "string"
        },
        "title": {
          "title": "ProductFull.title",
          "type": "string"
        },
        "description": {
          "title": "ProductFull.description",
          "type": "string"
        },
        "image": {
          "title": "ProductFull.image",
          "type": "string"
        },
        "price": {
          "title": "ProductFull.price",
          "type": "number"
        },
        "count": {
          "title": "ProductFull.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "image",
        "price",
        "count"
      ],
      "additionalProperties": false,
      "title": "ProductFull",
      "type": "object"
    },
    "ProductsData": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/ProductFull",
            "title": "ProductsData.products.[]"
          },
          "title": "ProductsData.products",
          "type": "array"
        },
        "total": {
          "title": "ProductsData.total",
          "type": "number"
        }
      },
      "required": [
        "products",
        "total"
      ],
      "additionalProperties": false,
      "title": "ProductsData",
      "type": "object"
    },
    "CreateProductParams": {
      "properties": {
        "id": {
          "title": "CreateProductParams.id",
          "type": "string"
        },
        "title": {
          "title": "CreateProductParams.title",
          "type": "string"
        },
        "description": {
          "title": "CreateProductParams.description",
          "type": "string"
        },
        "image": {
          "title": "CreateProductParams.image",
          "type": "string"
        },
        "price": {
          "title": "CreateProductParams.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "image",
        "price"
      ],
      "additionalProperties": false,
      "title": "CreateProductParams",
      "type": "object"
    },
    "NotFoundResponse": {
      "properties": {
        "message": {
          "title": "NotFoundResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "NotFoundResponse",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "error": {
          "title": "ErrorResponse.error",
          "type": "string"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};